[package]
name = "listprojects"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skim = "0.9.4"
structopt = "0.3.22"

[[bin]]
name = "project"
path = "src/main.rs"
